### ISSUE TITLE
Why it does't come to center? If there miss something?

### ISSUE THREAD

**Issue by TheKonka** [react-component/notification#164]
![image](https://user-images.githubusercontent.com/22173084/111034554-3c129400-8451-11eb-82b6-90513d0b62e7.png)

**Comment by anjanvb** [comment]
```css
.@{notificationPrefixCls} {
  position: fixed;
  transform: translate(-50%, 0);
  z-index: 1000;
 ....
```

That should center it.
