### ISSUE TITLE
自定义关闭的文字

### ISSUE THREAD

**Issue by zhujun24** [react-component/notification#3]
希望能实现自定义关闭的样式的接口，现在的Notification.js里是用`span`里包了字符`x`来实现关闭按钮，视觉稿上要用iconfont来实现关闭按钮
![b9039b58d2f401add6e7fb091c912582](https://cloud.githubusercontent.com/assets/7301773/8899246/57c82ffe-3464-11e5-9d22-e11cd00398ee.png)

**Comment by yiminghe** [comment]
.rc-notification-notice-close-x:after {
  content:''
}

**Comment by zhujun24** [comment]
视觉稿实现关闭按钮要用iconfont，而 CSS 的 content 里不能写 HTML 标签

**Comment by afc163** [comment]
```css
.rc-notification-notice-close-x:after {
  content:'\exxx';
  font-family: anticon;
}
```
